= Fulcro Rapid Application Development Tools

This library is currently an experiment. It should *not* be used in any kind of production
system unless you feel ok about forking it and maintaining the fork.  Once the ideas have
stabilied then I may do an official release with stable documentation and APIs.

Here are the goals:

* Declarative data model
  * Can be used to generate: forms, reports, data resolvers, etc.
* A Path-based auth management. That is to say: data always has a context, and that
  context implies security (a user can read their own emails). Often, figuring out the authorization
  in some specific context (i.e. a form) may require following the graph to figure out if the
  context has been established, and also to interact with authorizing it.

Some basic ideas:

* A state machine to manage auth context.  For example, you have auth in a google domain, a
facebook domain, and your company's domain.  Perhaps SSO gives you that, or perhaps you
have to auth against each in some way.  The idea is that the system can send events
to the auth state machine to verify (before running a full-stack query or making a mutation
button visible) that there is sufficient context for the request to succeed.  The query and mutation
can both imply what is being manipulated (the graph query could cross all three for example). So,
the UI routing and visibility could be tied to sending an event to the auth context machine with
a request to send *back* an event to the calling context when the auth is complete.  The auth systems
then run in parallel with the application logic.

* A given cluster of UI, though the colocated query, establishes a top-level context (e.g. `:account/id`),
and subqueries and joined via the graph query itself.  Pathom is used to traverse  this for data needs,
but it could also be traversed to derive the auth needs.

* A cluster of UI also establishes path-based contexts (e.g. `[account-id, mailbox, message-id]`) where a component
rendering the message is able to know the mailbox and account (accumulate identities along a UI path). This means
the composition of components can be used to easily establish what is *reachable* from a given location in the UI.
For example: say you're in an email with a message ID, and you know that a message ID has a sender email, and 
you know there is a resolver that can take an email address and turn that
that into a starting context for youtube videos posted by that person. This is already a feature of Pathom, but
it could be used *at development time* to do things like error checking, code completion, etc., and at
runtime to do things like mentioned in the prior point (resolve auth necessary to do something like use the
YouTube API).

* If all data is sufficiently declared, then we can also generate:
** Specs
** Data Resolvers (for the local domain database at least)
** Form UI (with a bit more declaration)
*** Correctly display/hide/make readonly fields
*** Fully automatic CRUD (even with nested sub-forms)
** Reports
*** Declarative inputs needed from user to run report
*** Rows/columns auto-derived based on resolvers/context

The new dynamic routing support would also make it possible to assemble most of a CRUD app with HTML5
routing, dynamic code loading (splitting), and arbitrary linkage of navigation with very little code.
Customizing the "chrome" of autogenerated things could also be declarative/pluggable, so that UI could even
be emitted (and customized) for web + native from the same declarations.

[ditaa]
-----


-----

