= Fulcro Rapid Application Development Tools

A library for Fulcro that adds pre-written elements for standing up production applications quickly.

WARNING: SNAPSHOT 16 moves rendering plugins to new libraries. This requires you update your project's dependencies.

== Usage

image:https://img.shields.io/clojars/v/com.fulcrologic/fulcro-rad.svg[link=https://clojars.org/com.fulcrologic/fulcro-rad]

Current SNAPSHOT CI status:
image:https://circleci.com/gh/fulcrologic/fulcro-rad/tree/develop.svg?style=svg["CircleCI", link="https://circleci.com/gh/fulcrologic/fulcro-rad/tree/develop"]

Current RELEASE CI status:
image:https://circleci.com/gh/fulcrologic/fulcro-rad/tree/master.svg?style=svg["CircleCI", link="https://circleci.com/gh/fulcrologic/fulcro-rad/tree/master"]

The RAD project has ambitious goals, but only one primary contributor who is very busy.

Documentation is currently available in the docstrings of the namespaces (most up-to-date), and you can refer to the
https://github.com/fulcrologic/fulcro-rad-demo[Fulcro RAD Demo] project (status varies).
There is a (likely inaccurate and out of date) start on a book at http://book.fulcrologic.com/RAD.html.

Unpaid questions or requests cannot be supported at this time.

Paid support for RAD and related libraries is available from http://www.fulcrologic.com[Fulcrologic, LLC].
You may ask questions on the #fulcro channel of http://clojurians.net/[Clojurians Slack].

== LICENSE

The MIT License (MIT)
Copyright (c), Fulcrologic, LLC

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit
persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
