= Authorization

The central concept we want to support in this feature is that there is a singleton authorization state machine that
keeps track of what the user is currently authorized to do, and can automatically do UI interactions to obtain the necessary
authorizations as an integration with the whole-app routing system (opted in by using a component definition API from this library)

Features:

* Pluggable system for doing authentication of users.
* Ability to detect the need for auth via attribute/mutation keyword/symbol.
* Can be asked to do explicit login (i.e. the implementation of a Login/Logout set of buttons in the UI)
* Must tolerate the need to do redirects (e.g. OpenID Connect)


WARNING: The remainder of this document is an incomplete and inaccurate picture of the current state of affairs.


[ditaa]
------

+----------------------+       +----------------------+
| Auth Provider (OAUTH)|       | Auth Provider (local)|
+----------------------+       +----------------------+
     ^                              ^
     |            (2)               |
     +------------------------------+
     |
     v
+----+-----------------+
| Auth State Machine   |
+-----------------+----+
   ^              |
   |              |
   | (1)          v (3)
+--+-------------------+
| ROUTING LAYER        |
+-----------------+----+
   ^              |
   |              v
+--+-------------------+
| UI Layer             |
+----------------------+

------

The core functionality is that some bit of UI that is about to be routed to:

1. An arbitrary state machine at the UI layer indicates a need to authorize a set of properties or mutations
by triggering `:event/authorize` on the well-known `::auth/machine` state machine. The event data for that
event includes the ID of the originating state machine and the set of properties/mutation symbols.
The auth machine is then responsible for ensuring that the current authorization context satisfies that.
Once it has made a clear decision it triggers
`:event/authorized` or `:event/permission-denied` to the original state machine. The *complete* event sent by the
original state machine is saved and is returned to the original machine on response.
2. The Auth UISM checks its state. If it does not have sufficient *authentication*
to even check authorization, then it will control the UI to obtains such
authentication. Once it has authentication, it could do a number of authorization
steps as well.  During this sequence it is allowed to save
and control the UI in whatever way is necessary to gather credentials, perhaps
even saving state in browser local storage and doing oauth redirects.
3. The auth UISM sends an event back to the originating UISM indicating the
result. That SM can then issue queries and routing instructions to properly
control the UI (based on any combination of factors, such as the
authorization really received).

== Authorization and Operation

Many UI elements can cope with (and often need to cope with) the fact
that they serve many different purposes for different user roles.

== Attribute Authorization

The generated mutations and resolvers are all derived from attribute and
entity declarations that indicate the desired protections. Thus, granularity
is at the field level and UI components (reports, forms, etc.) can auto
adjust to the data that is available to them.  For example a pathom
resolver might return the special value `:REDACTED` for something that
is queried but for which the user is not authorized. The UI component can
respond to this value by eliding the appropriate UI elements.

== Route Control

Some UI elements themselves require some level of authorization to even reach
(the attribute protections keep such UI from being a security hazard, but it
makes no sense to show a user a non-functional UI.)

Thus, when the auth system sends back an event that indicates insufficient
permissions, then the UI state machine controlling to desired UI target must
have some way of dealing with this:

* Aborting the route (return to where they came from).
* Showing a UI that indicates permission is denied.
* Others...
